apiVersion: apps/v1
kind: Deployment
metadata:
  name: song
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song
  template:
    metadata:
      labels:
        app: song
    spec:
      containers:
        - name: song
          image: intro2mset.azurecr.io/song:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_SERVER_URL
              value: "http://discovery:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                    name: song-db-secret
                    key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                    name: song-db-secret
                    key: USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: song-db-secret
                    key: PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10