server:
  port: 8080


s3:
  bucket-name: resource-bucket
  region: us-east-1
  endpoint: http://localhost:4566

spring:
  application:
    name: resource-service

  cloud:
    stream:
      bindings:
        resourceCreated-out-0:
          destination: resource-created-events
          content-type: application/json
      rabbit:
        bindings:
          resourceCreated-out-0:
            producer:
              exchange-type: topic
              routing-key-expression: "'resource.created'"
              retry:
                enabled: true
                max-attempts: 3
                initial-interval: 1000
                multiplier: 2
                max-interval: 5000
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:test}
    password: ${RABBITMQ_PASSWORD:test}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true

song-service:
  base-url: ${SONG_SERVICE_URL:lb://song-service}
  timeout:
    connect: 3s
    read: 5s
  retry:
    max-attempts: 3
    backoff:
      initial: 2000ms
      max: 5s

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: ${spring.application.name}
    description: "Service to manage resources"
